# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        NewsFeedBundle\Entity\User: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            entity: { class: NewsFeedBundle:User }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            # FIXME!
            anonymous: ~
            # activate different ways to authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login:
                login_path: login
                check_path: login

            logout:
                path:   /logout
                target: /                

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/edit,     roles: ROLE_USER }
        - { path: ^/password, roles: ROLE_USER }


